--- General stuff
require('plugins-setup')
require('settings')
require('colorscheme')
require('keybindings')
require('autocmd')

--- Plugin configs
require('colorizer-config')
require('lspinstall-config')
require('lspsaga-config')
require('telescope-config')
require('treesitter-config')
require('autocomplete-config')
require('ALE-config')
require('rnvimr-config')
require('bracey-config')
require('quickscope-config')
require('comment-config')
require('firenvim-config')
require('vimtex-config')
require('vimux-config')
require('gitfugative-config')
require('emmet-config')
require('lspkind-config')
require('startify-config')
require('autopairs-config')
require('lualine-config')
require('indentline-config')
require('hop-config')
