--- General stuff
require('plugins-setup')
require('settings')
require('colorscheme')
require('keybindings')
require('autocmd')

--- Plugin configs
require('colorizer-config')
require('lspinstall-config')
require('lspsaga-config')
require('telescope-config')
require('treesitter-config')
require('autocomplete-config')
require('ALE-config')
require('seiya-config')
require('rnvimr-config')
require('bracey-config')
require('quickscope-config')
require('nerdCommenter-config')
require('firenvim-config')
require('vimtex-config')
require('vimux-config')
require('gitfugative-config')
require('vimSneak-config')
require('emmet-config')
require('lspkind-config')
require('peekup-config')
require('startify-config')

local scan = require'plenary.scandir'
local res = scan.scan_dir('.', { hidden = true, depth = 1 })
print(vim.inspect(res))
